image:
  repository: ghcr.io/vaelqorix/vaelqorix-api
  tag: "stable"
  pullPolicy: IfNotPresent

replicaCount: 2

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi
