apiVersion: v1
kind: ConfigMap
metadata:
  name: aresx-config
data:
  ENV: "production"
  LOG_LEVEL: "INFO"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  ZENTHRA_CORRELATION_ENABLED: "true"
  ZENTHRA_CORRELATION_INTERVAL_SEC: "60"
  ZENTHRA_CORRELATION_STARTUP_DELAY_SEC: "10"
  BOOTSTRAP_ADMIN_ENABLED: "false"
